### ISSUE TITLE
[Bug] User Settings will not be implemented in this fashion

### ISSUE THREAD

**Issue by FullSol** [Revature-Leafbound/Leafbound-API#52]
https://github.com/Revature-Leafbound/Leafbound-API/blob/5b2970d3bd1942d0347fd49b2373d078f33db389/src/main/java/com/leafbound/models/User.java#L53

Please remove the reference to the user settings table.
- There will not be a user settings table
- We do not need the model property
- Remove all annotations for this property as well.
- This will be lines 50 - 53 removed from the file.

**Comment by AdamLucasCoding** [comment]
Understood. First thing tomorrow I'll update this.
