### ISSUE TITLE
[Endpoint Testing] Orders

### ISSUE THREAD

**Issue by L3viathon** [Revature-Leafbound/Leafbound-API#96]

**Comment by vidyabineesh** [comment]
Here is an update on Order endpoint testing:

http://localhost:8080/api/v1/orderid/1fbcba9e-16d0-425d-b2b2-1c24aea4f8de	     - Passed
http://localhost:8080/api/v1/orderall						                             - Passed
**http://localhost:8080/api/v1/orderdate						                             - Failed**
http://localhost:8080/api/v1/orderupdate						                     - Passed
http://localhost:8080/api/v1/orderdelete						                     - Passed

**Comment by FullSol** [comment]
Hi @vidyabineesh ,

Most of these routes have been updated, just the path to connect to the route in most cases.

The date route should not be working correctly.

Thanks,
Calvin

**Comment by FullSol** [comment]
The new routes:

- /api/v1/order (POST) Create a new order
- /api/v1/order/{id} (GET) Get order by Id
- /api/v1/order/{id} (DELETE) Delete Order by Id
- /api/v1/order/{id} (PATCH) Update order by id - also requires a body still
- /api/v1/order/all (GET) Get all order
- /api/v1/order/date/{orderDate} (GET) Get order by date

**Comment by FullSol** [comment]
Also, not these can be tested by going to [the swagger docs](http://localhost:8080/v2/api-docs) when your application is running.

**Comment by vidyabineesh** [comment]
- /api/v1/order (POST) Create a new order

- /api/v1/order/{id} (GET) Get order by Id - Passed
E.g.: http://localhost:8080/api/v1/order/470f32b5-cc0f-4482-8abe-9b10617609a8

- /api/v1/order/{id} (DELETE) Delete Order by Id - Failed with error " Failed to convert value of type 'java.lang.String' to required type 'int';"
E.g.: http://localhost:8080/api/v1/order/12e59611-71f1-4cb0-b2db-c876dd677325

- /api/v1/order/{id} (PATCH) Update order by id - Passed 
E.g.: http://localhost:8080/api/v1/order/470f32b5-cc0f-4482-8abe-9b10617609a8

- /api/v1/order/all (GET) Get all orders - Passed 
E.g.: http://localhost:8080/api/v1/order/all

- /api/v1/order/date/{orderDate} (GET) Get order by date - Failed 
 Test case 1: Only one matching record in the database with input date - Passed
 Test case 2: Multiple matching records in the database with input date - Failed
